title: "Partha Biswas – AI/ML Portfolio"
description: "Agentic AI and projects showcase"

remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme

collections:
  projects:
    output: true
